### ISSUE TITLE
can't remove coloured travelnets

### ISSUE THREAD

**Issue by SwissalpS** [mt-mods/travelnet#10]
node.name contains colour, so needs to be checked too.

example: travelnet:travelnet_red

https://github.com/mt-mods/travelnet/blob/73fc37ee20c8812ad2a5b6871b77349a451f951f/on_receive_fields.lua#L40

**Comment by Panquesito7** [comment]
Working on a fix.

**Comment by Panquesito7** [comment]
Weird, this code doesn't work properly in MT 5.4.0-dev:

```lua
      -- List of the names of the colors
      -- that various travelnets use.
      local colors = {
         "red", "blue", "green",
         "black", "white"
      }

      for _, color in ipairs(colors) do
         if( node and node.name and node.name == "travelnet:travelnet") then
            description = "travelnet box"
         elseif ( node and node.name and node.name == "travelnet:travelnet_" .. color) then -- Colored travelnets
            description = color .. " travelnet box"
         elseif( node and node.name and node.name == "travelnet:elevator") then
            description = "elevator"
         elseif( node and node.name and node.name == "locked_travelnet:travelnet") then
            description = "locked travelnet"
         else
            minetest.chat_send_player(name, "Error: Unknown node.");
            return
         end
      end
```

Is there something I'm doing wrong?

**Comment by SwissalpS** [comment]
it's not a clean approach, it is repeatedly checking for the same names. Better would be to check
`node.name:sub(1, 19) == 'travelnet:travelnet'` in the line you concatenate the colour. This way no loop is needed.

Even cleaner would be to have a table with all valid node names with their description:
```
local t = {}
t['travelnet:travelnet'] = 'travelnet box'
t['travelnet:travelnet_red'] = 'red travelnet box'
t['travelnet:elevator'] = 'elevator'
-- ... insert the rest, optionally build this table once with a loop when mod is loaded

local description = node and node.name and t[node.name]
if not description then
  -- ... send fail chat message
  return
end

-- ... proceed to remove
```

**Comment by SwissalpS** [comment]
On another note, a bit nit-picky: the many parenthesis used in this code are not helpful.
Example line 121 and onward:
```
if( not( owner_name ) or not( station_name) .... ) then .... end
```
If parenthesis, then like this:
```
if (not owner_name) or (not station_name) .... then .... end
```
But it's cleaner and readable enough:
```
if not owner_name
  or not station_name
  or not station_network
  or not travelnet.targets[owner_name]
  or not travelnet.targets[owner_name][station_network]
then
  .....
end
```

**Comment by BuckarooBanzay** [comment]
Ugh, i didn't test this properly, maybe i had the `protection_bypass` granted to myself :facepalm:

Maybe something like this helps:
https://github.com/mt-mods/travelnet/blob/efa07b17bd56ef5b63b93c8dcafb1a2a66589c9d/on_receive_fields.lua#L224-L225

It should only check the for the `travelnet` group on the node, not all the registered travelnets...

@Panquesito7 let me know when you need help

**Comment by SwissalpS** [comment]
> It should only check the for the `travelnet` group on the node, not all the registered travelnets...

even better, yes :D

**Comment by OgelGames** [comment]
Fixed by checking for "tavelnet" group, also added check for locked elevator (https://github.com/Sokomine/locked_travelnet/blob/master/locked_elevator.lua#L5).

> On another note, a bit nit-picky: the many parenthesis used in this code are not helpful.
> Example line 121 and onward:
> 
> ```
> if( not( owner_name ) or not( station_name) .... ) then .... end
> ```

There's a lot of that, needs a cleanup at some stage... 😖
