### ISSUE TITLE
Texture z fighting after adding colored travelnets

### ISSUE THREAD

**Issue by S-S-X** [mt-mods/travelnet#12]
Happens more or less but bit annoying when it happens, did not take too much effort to get this:
![screenshot_20210129_190014](https://user-images.githubusercontent.com/50966843/106304737-670ba480-6264-11eb-9695-e5bb8765776f.png)

Happens at least with 5.3.0 Windows and 5.4.0-dev Linux, both completely different hardware.

**Comment by BuckarooBanzay** [comment]
i'm having trouble reproducing this, can you give me your graphic settings? Do you use opengl?

**Comment by S-S-X** [comment]
Seems that few other players also reported same thing in chat, both after adding colored travelnets:
```
<chi> seems i get generateImage errors when around travelnets
<chi> and z-fighting with the back wall
<FeXoR> Funny. This Travelnet Box doesn't have the graphics glitch at it's backside most have.
<FeXoR> Did the graphics glitch at the back wall of a travelnet box also appear in the old version?
```

Here's my config:
```ini
screen_w = 1920
screen_h = 1080
fullscreen = true
fullscreen_bpp = 32
vsync = false
3d_mode = none
video_driver = opengl

connected_glass = true
opaque_water = false
enable_waving_water = true
enable_waving_plants = true
enable_waving_leaves = true
leaves_style = fancy
node_highlighting = box
enable_fog = true

bilinear_filter = false
trilinear_filter = true
anisotropic_filter = true
mip_map = true
generate_normalmaps = true
enable_bumpmapping = true
tone_mapping = true
enable_parallax_occlusion = true
fsaa = 8
```

It seems that this is bit more likely to happen when some distance between you and travelnet. Note crosshair position in following 2 screenshots:
![screenshot_20210201_151338](https://user-images.githubusercontent.com/50966843/106468468-a3c6de00-64a6-11eb-8d05-51b8fab878e9.png)
![screenshot_20210201_151333](https://user-images.githubusercontent.com/50966843/106468473-a4f80b00-64a6-11eb-9b1a-8c3de6ab669d.png)

**Comment by BuckarooBanzay** [comment]
Does this also happen in a local setup? The "generateTexture" error reminds of some texture-caching issue...

**Comment by Panquesito7** [comment]
Well, I have been using this fork of the mod for a while and cannot reproduce anything. Using 5.4.0-dev and the latest version of this mod. 🤷‍♂️

**Comment by S-S-X** [comment]
> Does this also happen in a local setup? The "generateTexture" error reminds of some texture-caching issue...

I believe that The "generateTexture" error probably only happened to 1 out of 3 users who reported this problem.

> Using 5.4.0-dev and the latest version of this mod.

Latest mod for all users reporting this problem, can't say mt version for others but I've tested only with 5.3.0

> have been using this fork of the mod for a while and cannot reproduce anything.

All reports came very soon after colored travelnet upgrade, I've never seen this before that update but noticed it very soon after update. So "using for a while" does not really tell anything useful unless it is heavy usage during last month with large user base.

**Comment by S-S-X** [comment]
Some additional info about what it takes for me to actually see this, also turned view distance down to see if it has anything to do with it. Does not seem to. Usually using 240 - 1000 max distance.

For these travelnets it seems that I cannot reproduce issue:

![screenshot_20210201_214038](https://user-images.githubusercontent.com/50966843/106509365-36cb3c80-64d6-11eb-8c88-827d89758886.png)

Here I can get some mild flickering if trying hard enough, however very hard to notice or get stable enough for screenshot:

![screenshot_20210201_214014](https://user-images.githubusercontent.com/50966843/106509360-359a0f80-64d6-11eb-8f4b-507d2a3c8e12.png)

Here, when distance to travelnet is about 20 nodes I can get z fighting very clear and frequent:

![screenshot_20210201_214048](https://user-images.githubusercontent.com/50966843/106509373-38950000-64d6-11eb-8167-3fd32bee3b4a.png)

**Comment by S-S-X** [comment]
Here's screenshot from some bit earlier 5.4.0-dev Linux version, earlier stuff was 5.3.0 Windows.

![screenshot_20210201_220815](https://user-images.githubusercontent.com/50966843/106512434-451b5780-64da-11eb-974b-02f33e7059c9.png)

**Comment by OgelGames** [comment]
So it turns out this was caused by one of my commits (https://github.com/mt-mods/travelnet/commit/703a9392045fc789cc32a22c221d3630fdf6c105) that somehow ended up blanking the front texture: https://github.com/mt-mods/travelnet/blob/master/textures/travelnet_travelnet_front_color.png

No clue how it happened, but it should be easy to fix 😉

**Comment by BuckarooBanzay** [comment]
thanks @OgelGames :+1:
