### ISSUE TITLE
attempt to index local 'network' (a nil value) in b81650c/15.07.2021

### ISSUE THREAD

**Issue by Festus1965** [mt-mods/travelnet#20]
under MultiCraft 2.0.0, fork of 5.4.1
just downloaded last - b81650c/15.07.2021 - I get 

```
ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod '' in callback node_on_receive_fields(): .../thomas/.multicraft/mods/travelnet/on_receive_fields.lua:136: attempt to index local 'network' (a nil value)
ERROR[Main]: stack traceback:
ERROR[Main]: 	.../thomas/.multicraft/mods/travelnet/on_receive_fields.lua:136: in function <.../thomas/.multicraft/mods/travelnet/on_receive_fields.lua:4>
```

line 136 at me:
`local target_station = network[fields.target]`

maybe catch out with:

if network[fields.target] == nil then
target_station = ?? -- for line 139
else
local target_station = network[fields.target]
end

??? or same as 139 to 145 for nil

**Comment by BuckarooBanzay** [comment]
> under MultiCraft 2.0.0, fork of 5.4.1

Yeah, but no: this isn't your dump for multicraft-bugs :rage:
please use an official minetest version (_you_ should now better)

Anyway: if you want that particular bug fixed, try to provide the position and metadata of the faulty travelnet/elevator.

This looks like wrong/missing metadata (i've never seen that error in a proper/non-corrupted world)

**Comment by Festus1965** [comment]
interresting
as MultiCraft 2.0.0 is a fork of Minetest 5.4.1
what is this tree here then to 
* https://github.com/Sokomine/travelnet
* https://github.com/mt-mods/travelnet

whatever: as long MultiCraft is meant to be Minetest and listed in servers.Mintest.net it IS minetest ... says the devs etc.
I gave mt months to decide ... now also you have to accept this.

I am just to lazy still to be mineTESTER and made my own coding there, if x == nil ... and will see.

But even if not have seen this before, and if it is from a corrupt,
good coding IS to avoid crashes as if failures, this should result in a report of possible corrupt, not in crash.

**Comment by Festus1965** [comment]
no crash now with the good programmer solution, so avaid any issue and basically a crash:

just:
2021-09-12 00:02:41: WARNING[Server]: Undeclared global variable "target_station" accessed at .../thomas/.multicraft/mods/travelnet/on_receive_fields.lua:149
now

sure, I have to find out what is the reason, but this is more relaxing when the server don't crash when I would find that travelnet station !!!

**Comment by Panquesito7** [comment]
> no crash now with the good programmer solution, so avaid any issue and basically a crash:
> 
> just:
> 2021-09-12 00:02:41: WARNING[Server]: Undeclared global variable "target_station" accessed at .../thomas/.multicraft/mods/travelnet/on_receive_fields.lua:149
> now
> 
> sure, I have to find out what is the reason, but this is more relaxing when the server don't crash when I would find that travelnet station !!!

Awesome, glad to see you fixed it! Would you like to make a pull request or share your bugfix with us? 🙂

**Comment by Festus1965** [comment]
sure ? 
> Yeah, but no: this isn't your dump for multicraft-bugs rage

When the code is only for 5.x minetest I am wrong here, I think !
But as long MultiCraft is in the Minetest serverlist, it IS minetest ...

that is the latest version, but mod is already out = folder mods-failed and not used anymore:
`	-- by Thomas as of second/third time = network[fields.target] == nil !!!
	if network[fields.target] == nil then
		minetest.chat_send_player(name,
				S("Station '@1' does not exist. = ?")
		)
		travelnet.update_formspec(pos, name, nil)
		return
	end

	-- will it work then outside ? and not do the crash nil ???
	local target_station = network[fields.target]`

I stepped back to older version  - what is the saver way, as I know already sometime not worth to fix issues, as devs make new engine versions, and the fun to fix problems begin again ...
