### ISSUE TITLE
editable travelnets and elevators

### ISSUE THREAD

**Issue by SwissalpS** [mt-mods/travelnet#23]
Have started here https://github.com/mt-mods/travelnet/tree/editableStation on editableStation branch.

**Comment by SwissalpS** [comment]
I don't intend on smoothing out the translations until behaviour and bugs have been agreed and cleaned up.

**Comment by BuckarooBanzay** [comment]
pulled your branch into the test-server, everything is working so far :+1: 
The only annoying thing is that you have to punch the travelnet to reload the station-list again but thats not a new thing :shrug:
