### ISSUE TITLE
Use settings instead of a config script

### ISSUE THREAD

**Issue by oversword** [mt-mods/travelnet#38]
We should use minetest settings instead of a config script so people can configure this properly and not via code.

Ideally everything in `config.lua` would be turned into a setting, but there are some functions defined in there so everything except those.

I have made a mod that makes this easy, even for complex structures: https://github.com/oversword/config

Let me know if you think it's okay to use this as a dependency of this mod

**Comment by wsor4035** [comment]
honestly seems rather over complicated for this use case. but yes global variable fields in config.lua should be replaced with the minetest setting api

**Comment by oversword** [comment]
Yeah it's not *really* required here, but it will make it easier to expand in the future, and it does all the fallbacks to the old setting methods automatically. We can also define the crafts in the settings to if we like, as that mod will parse tables or even allow for a custom type that lets you defined the craft however you like

**Comment by oversword** [comment]
One major issue for this task will be making sure this works alongside the legacy `config.lua` as we don't want to break compat.

**Comment by wsor4035** [comment]
for the record im opposed to using it because it seems to be a giant overcomplication of just using the mientest setting api

**Comment by wsor4035** [comment]
> One major issue for this task will be making sure this works alongside the legacy `config.lua` as we don't want to break compat.

in order to use the config.lua file you had to effectively fork the mod for it to work so personally dropping support for the file is fine by me. however support should be kept for overriding the functions for legacy compat. however other devs of this org may point out something i missed as to why the above isnt the best idea
