### ISSUE TITLE
Removing travelnet doesn't remove it from network

### ISSUE THREAD

**Issue by OgelGames** [mt-mods/travelnet#57]
1. Place two travelnets and configure them to be on the same network
2. Remove one of the travelnets
3. The removed travelnet is still visible on the other travelnet

Also when removing a travelnet there is an error message in chat: `Error: Could not find the station that is to be removed.`

**Comment by oversword** [comment]
Looking into this, just experienced in production. Hopefully this is only a specific scenario...

Will also produce a cleanup script to fix existing data

**Comment by oversword** [comment]
@OgelGames Do you have any specifics on this? Can't replicate with a basic setup.

The live travelnet I'm looking at is part of an old network (pre-change). Is that the same for you too?

**Comment by oversword** [comment]
Okay here's a setup:

2. Place a travelnet, set the name to "a", use the other default values
3. Place another travelnet, set the name to "b", use the other default values
4. Place another travelnet, set the name to "c", use the other default values
5. Confirm you can travel between all of them
6. Go to travelnet b, click "edit", then "remove"
7. Place another travelnet, set the name to "b"

- You get a name conflict error even though it's been removed
- If you place the new travelnet in the same place as the old one, you will be able to travel to that station even though it is not configured, and the "b" station will not be remove from the other travelnet's lists

**Comment by oversword** [comment]
In my specific scenario I placed a travelnet in the same place then connected it to a different network, now they both think they have a travelnet in the same spot xD Quite a tangle

**Comment by oversword** [comment]
Think I've fixed this, @OgelGames hopefully my descriptions of what happened should help you fix your data
