### ISSUE TITLE
Remove chat message when teleporting

### ISSUE THREAD

**Issue by Aracaa** [mt-mods/travelnet#87]
Maybe it's an unpopular opinion, this is why I open this ticket. 

Using a lot travelnet-boxes, I feel like the message send in chat each time we teleport is too much

![image](https://github.com/mt-mods/travelnet/assets/14837771/691c86f4-0f48-4cc9-b808-3578b116253c)

What do you think of removing this message ? 

`transport_player.lua` line 35

**Comment by BuckarooBanzay** [comment]
> What do you think of removing this message ?

Sounds good to me :+1:
