### ISSUE TITLE
Can't craft travelbox

### ISSUE THREAD

**Issue by kanduvisla** [mt-mods/travelnet#90]
Is it just me or can't I craft the travelbox? I do have all the recipes to craft a colored travelbox from an existing travelbox, but I cannot seem to craft the main thing.

The recipe in the description does not work.

**Comment by OgelGames** [comment]
Can you provide your mod list? It should work with either Minetest Game, Mineclone 2, or Mineclonia.

**Comment by kanduvisla** [comment]
Sure, these are my mods installed:

```
animalia
cblocks
creatura
depth_finder
livingdesert
livingjungle
minetest_mod_weather
moretorches
naturalbiomes
travelnet
```

**Comment by BuckarooBanzay** [comment]
> craft it by filling the right and left column with glass; place in the middle column (from top to bottom): steel, mese, steel 

i think the wording might confuse some people here ^

this is the proper recipe:
https://github.com/mt-mods/travelnet/blob/fad216db52b8fc8fafa11868d80c9e35c4b4a7ac/config.lua#L26-L29

@kanduvisla can you try that?

**Comment by kanduvisla** [comment]
Oh, I think I had a brainfart. It's supposed to be a mese **block**, I thought a mese **crystal**.

Sorry, my bad!
